import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { 
  Shield, 
  KeyRound, 
  Plus, 
  Sparkles, 
  Copy, 
  Check, 
  Trash2, 
  RefreshCw, 
  Sliders, 
  Terminal, 
  Download, 
  Upload, 
  RotateCcw, 
  Lock, 
  X, 
  Eye, 
  EyeOff, 
  CheckCircle2, 
  AlertCircle,
  Layers,
  Database,
  Globe,
  HardDrive,
  Cloud
} from 'lucide-react';
import { AccessPass, CustomField, CustomFieldType, Profile, ApiConfig, GoogleDriveBackendConfig } from '../types';
import { createAutoGeneratedPass, autoGeneratePasscode } from '../utils/passcodeGenerator';
import { ApiConfigTab } from './ApiConfigTab';
import { GoogleDriveTab } from './GoogleDriveTab';

interface AdminPanelProps {
  isOpen: boolean;
  onClose: () => void;
  initialTab?: 'passes' | 'schema' | 'drive' | 'api' | 'python' | 'settings';
  accessPasses: AccessPass[];
  customFields: CustomField[];
  profiles: Profile[];
  adminPin: string;
  apiConfig: ApiConfig;
  driveConfig: GoogleDriveBackendConfig;
  onUpdatePasses: (passes: AccessPass[]) => void;
  onUpdateFields: (fields: CustomField[]) => void;
  onUpdateProfiles: (profiles: Profile[]) => void;
  onUpdateAdminPin: (pin: string) => void;
  onUpdateApiConfig: (config: ApiConfig) => void;
  onUpdateDriveConfig: (config: GoogleDriveBackendConfig) => void;
  onImportDriveData: (data: { profiles: Profile[]; fields: CustomField[]; passes: AccessPass[] }) => void;
  onResetDatabase: () => void;
  onOpenPythonHub: () => void;
}

export const AdminPanel: React.FC<AdminPanelProps> = ({
  isOpen,
  onClose,
  initialTab,
  accessPasses,
  customFields,
  profiles,
  adminPin,
  apiConfig,
  driveConfig,
  onUpdatePasses,
  onUpdateFields,
  onUpdateProfiles,
  onUpdateAdminPin,
  onUpdateApiConfig,
  onUpdateDriveConfig,
  onImportDriveData,
  onResetDatabase,
  onOpenPythonHub,
}) => {
  const [activeTab, setActiveTab] = useState<'passes' | 'schema' | 'drive' | 'api' | 'python' | 'settings'>('drive');

  useEffect(() => {
    if (initialTab && isOpen) {
      setActiveTab(initialTab);
    }
  }, [initialTab, isOpen]);

  // New Pass Generation State
  const [passRole, setPassRole] = useState<'viewer' | 'editor'>('viewer');
  const [passLabel, setPassLabel] = useState('');
  const [passPrefix, setPassPrefix] = useState<'USER' | 'AGENT' | 'CLIENT' | 'MEMBER'>('AGENT');
  const [latestGeneratedPass, setLatestGeneratedPass] = useState<AccessPass | null>(null);
  const [copiedId, setCopiedId] = useState<string | null>(null);
  const [showPasscodes, setShowPasscodes] = useState<Record<string, boolean>>({});

  // New Field Builder State
  const [fieldLabel, setFieldLabel] = useState('');
  const [fieldType, setFieldType] = useState<CustomFieldType>('text');
  const [fieldOptions, setFieldOptions] = useState('');
  const [fieldPlaceholder, setFieldPlaceholder] = useState('');
  const [fieldShowInTable, setFieldShowInTable] = useState(true);
  const [fieldRequired, setFieldRequired] = useState(false);
  const [fieldSuccessMsg, setFieldSuccessMsg] = useState<string | null>(null);

  // Settings State
  const [newPin, setNewPin] = useState('');
  const [pinChangeMsg, setPinChangeMsg] = useState<string | null>(null);

  if (!isOpen) return null;

  // Auto-Generate New Access Pass (no typing needed to gen, 1-click!)
  const handleAutoGeneratePass = () => {
    const newPass = createAutoGeneratedPass({
      role: passRole,
      label: passLabel.trim() || undefined,
      prefix: passPrefix,
    });

    const updated = [newPass, ...accessPasses];
    onUpdatePasses(updated);
    setLatestGeneratedPass(newPass);
    setPassLabel('');
  };

  const handleTogglePassActive = (id: string) => {
    const updated = accessPasses.map((p) =>
      p.id === id ? { ...p, isActive: !p.isActive } : p
    );
    onUpdatePasses(updated);
  };

  const handleRegeneratePasscode = (id: string) => {
    const newCode = autoGeneratePasscode();
    const updated = accessPasses.map((p) =>
      p.id === id ? { ...p, passcode: newCode } : p
    );
    onUpdatePasses(updated);
  };

  const handleDeletePass = (id: string) => {
    if (confirm('Permanently delete this access pass?')) {
      const updated = accessPasses.filter((p) => p.id !== id);
      onUpdatePasses(updated);
      if (latestGeneratedPass?.id === id) {
        setLatestGeneratedPass(null);
      }
    }
  };

  const handleCopyCredentials = (pass: AccessPass) => {
    const text = `Username: ${pass.username}\nPasscode: ${pass.passcode}\nRole: ${pass.role}`;
    navigator.clipboard.writeText(text);
    setCopiedId(pass.id);
    setTimeout(() => setCopiedId(null), 2000);
  };

  // Add Custom Field
  const handleCreateField = (e: React.FormEvent) => {
    e.preventDefault();
    if (!fieldLabel.trim()) return;

    const slug = fieldLabel.toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_+|_+$/g, '');
    const optionsArray = fieldOptions.trim()
      ? fieldOptions.split(',').map((s) => s.trim()).filter(Boolean)
      : undefined;

    const newField: CustomField = {
      id: `f_${Date.now()}`,
      label: fieldLabel.trim(),
      key: slug,
      type: fieldType,
      options: optionsArray,
      placeholder: fieldPlaceholder.trim() || undefined,
      showInTable: fieldShowInTable,
      required: fieldRequired,
      createdAt: new Date().toISOString(),
    };

    onUpdateFields([...customFields, newField]);
    setFieldLabel('');
    setFieldOptions('');
    setFieldPlaceholder('');
    setFieldSuccessMsg(`Field "${newField.label}" created! It now appears on all profile forms and database views.`);
    setTimeout(() => setFieldSuccessMsg(null), 3000);
  };

  const handleDeleteField = (fieldId: string) => {
    if (confirm('Delete this custom field? Existing values will be retained in history.')) {
      onUpdateFields(customFields.filter((f) => f.id !== fieldId));
    }
  };

  const handleToggleFieldTable = (fieldId: string) => {
    onUpdateFields(
      customFields.map((f) =>
        f.id === fieldId ? { ...f, showInTable: !f.showInTable } : f
      )
    );
  };

  // Export JSON
  const handleExportJSON = () => {
    const data = {
      profiles,
      customFields,
      accessPasses,
      exportedAt: new Date().toISOString(),
      version: '1.0.0',
    };
    const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `nexusdb_backup_${new Date().toISOString().slice(0, 10)}.json`;
    a.click();
    URL.revokeObjectURL(url);
  };

  // Import JSON
  const handleImportJSON = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    const reader = new FileReader();
    reader.onload = (loadEvt) => {
      try {
        const parsed = JSON.parse(String(loadEvt.target?.result));
        if (parsed.profiles) onUpdateProfiles(parsed.profiles);
        if (parsed.customFields) onUpdateFields(parsed.customFields);
        if (parsed.accessPasses) onUpdatePasses(parsed.accessPasses);
        alert('Database successfully imported from JSON backup!');
      } catch (err) {
        alert('Failed to parse JSON file.');
      }
    };
    reader.readAsText(file);
  };

  const handleChangePin = (e: React.FormEvent) => {
    e.preventDefault();
    if (newPin.trim().length >= 4) {
      onUpdateAdminPin(newPin.trim());
      setNewPin('');
      setPinChangeMsg('Admin PIN updated successfully!');
      setTimeout(() => setPinChangeMsg(null), 3000);
    }
  };

  return (
    <div
      id="admin-panel-overlay"
      className="fixed inset-0 z-50 flex items-center justify-center p-3 sm:p-6 bg-black/85 backdrop-blur-md overflow-y-auto"
    >
      <motion.div
        initial={{ opacity: 0, scale: 0.96 }}
        animate={{ opacity: 1, scale: 1 }}
        exit={{ opacity: 0, scale: 0.96 }}
        className="w-full max-w-4xl max-h-[92vh] bg-[#0d131f] border border-slate-800 rounded-2xl shadow-2xl flex flex-col overflow-hidden text-slate-200"
      >
        {/* Modal Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-slate-800/80 bg-slate-900/70">
          <div className="flex items-center gap-3">
            <div className="w-9 h-9 rounded-xl bg-purple-500/10 border border-purple-500/20 text-purple-400 flex items-center justify-center">
              <Shield className="w-5 h-5" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h2 className="text-base font-bold text-white">
                  Administrator Console
                </h2>
                <span className="px-2 py-0.5 rounded text-[11px] font-mono bg-purple-950 text-purple-300 border border-purple-800">
                  Schema & Access Engine
                </span>
              </div>
              <p className="text-xs text-slate-400">
                Auto-generate passcodes, configure dynamic database fields, and control credentials
              </p>
            </div>
          </div>
          <button
            type="button"
            onClick={onClose}
            className="p-1.5 text-slate-400 hover:text-white rounded-lg hover:bg-slate-800 transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Tab Switcher */}
        <div className="flex items-center px-6 pt-3 border-b border-slate-800/80 bg-slate-900/40 gap-4 overflow-x-auto no-scrollbar">
          <button
            type="button"
            onClick={() => setActiveTab('passes')}
            className={`pb-3 text-xs font-semibold border-b-2 flex items-center gap-2 transition-colors shrink-0 cursor-pointer ${
              activeTab === 'passes'
                ? 'border-blue-500 text-blue-400'
                : 'border-transparent text-slate-400 hover:text-slate-200'
            }`}
          >
            <KeyRound className="w-4 h-4" />
            <span>Auto-Generated Passcodes ({accessPasses.length})</span>
          </button>

          <button
            type="button"
            onClick={() => setActiveTab('schema')}
            className={`pb-3 text-xs font-semibold border-b-2 flex items-center gap-2 transition-colors shrink-0 cursor-pointer ${
              activeTab === 'schema'
                ? 'border-purple-500 text-purple-400'
                : 'border-transparent text-slate-400 hover:text-slate-200'
            }`}
          >
            <Layers className="w-4 h-4" />
            <span>Custom Fields Builder ({customFields.length})</span>
          </button>

          <button
            type="button"
            onClick={() => setActiveTab('drive')}
            className={`pb-3 text-xs font-semibold border-b-2 flex items-center gap-2 transition-colors shrink-0 cursor-pointer ${
              activeTab === 'drive'
                ? 'border-emerald-500 text-emerald-400'
                : 'border-transparent text-slate-400 hover:text-slate-200'
            }`}
          >
            <Cloud className="w-4 h-4" />
            <span>Cloud & Cloud JSON Sync</span>
            <span className="w-2 h-2 rounded-full bg-emerald-400 animate-pulse"></span>
          </button>

          <button
            type="button"
            onClick={() => setActiveTab('api')}
            className={`pb-3 text-xs font-semibold border-b-2 flex items-center gap-2 transition-colors shrink-0 cursor-pointer ${
              activeTab === 'api'
                ? 'border-indigo-500 text-indigo-400'
                : 'border-transparent text-slate-400 hover:text-slate-200'
            }`}
          >
            <Globe className="w-4 h-4" />
            <span>API & Web Form Sync</span>
          </button>

          <button
            type="button"
            onClick={() => setActiveTab('python')}
            className={`pb-3 text-xs font-semibold border-b-2 flex items-center gap-2 transition-colors shrink-0 cursor-pointer ${
              activeTab === 'python'
                ? 'border-emerald-500 text-emerald-400'
                : 'border-transparent text-slate-400 hover:text-slate-200'
            }`}
          >
            <Terminal className="w-4 h-4" />
            <span>Python SQLite Script</span>
          </button>

          <button
            type="button"
            onClick={() => setActiveTab('settings')}
            className={`pb-3 text-xs font-semibold border-b-2 flex items-center gap-2 transition-colors shrink-0 cursor-pointer ${
              activeTab === 'settings'
                ? 'border-amber-500 text-amber-400'
                : 'border-transparent text-slate-400 hover:text-slate-200'
            }`}
          >
            <Sliders className="w-4 h-4" />
            <span>Database Backup & PIN</span>
          </button>
        </div>

        {/* Tab 1: Auto-Generated Passcodes & User Access Manager */}
        {activeTab === 'passes' && (
          <div className="flex-1 overflow-y-auto p-6 space-y-6">
            {/* Primary Action Card: 1-Click Auto-Generate */}
            <div className="p-5 rounded-2xl bg-gradient-to-r from-blue-950/40 via-indigo-950/30 to-purple-950/40 border border-blue-800/50 shadow-xl">
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
                <div>
                  <span className="inline-flex items-center gap-1.5 text-xs font-semibold text-blue-400 uppercase tracking-wider mb-1">
                    <Sparkles className="w-3.5 h-3.5 text-amber-400" />
                    Auto-Generate Access Credentials
                  </span>
                  <h3 className="text-base font-bold text-white">
                    Instant Passcode Generator
                  </h3>
                  <p className="text-xs text-slate-400 max-w-lg mt-0.5">
                    Click to auto-generate a unique cryptographic Username and Passcode without typing.
                  </p>
                </div>

                <button
                  type="button"
                  id="btn-auto-generate-pass"
                  onClick={handleAutoGeneratePass}
                  className="px-5 py-2.5 bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-500 hover:to-indigo-500 text-white font-medium text-xs rounded-xl shadow-lg shadow-blue-600/30 flex items-center justify-center gap-2 transition-all shrink-0 cursor-pointer active:scale-[0.98]"
                >
                  <KeyRound className="w-4 h-4" />
                  <span>⚡ Auto-Generate New Pass</span>
                </button>
              </div>

              {/* Generator Options */}
              <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 mt-4 pt-4 border-t border-slate-800/80 text-xs">
                <div>
                  <label className="block text-slate-400 mb-1 font-medium">Role Permission</label>
                  <select
                    value={passRole}
                    onChange={(e) => setPassRole(e.target.value as any)}
                    className="w-full px-2.5 py-1.5 bg-slate-900 border border-slate-700/80 rounded-lg text-white text-xs focus:outline-none focus:ring-1 focus:ring-blue-500"
                  >
                    <option value="viewer">Viewer (Read-Only Access)</option>
                    <option value="editor">Editor (Can Add & Edit Records)</option>
                  </select>
                </div>

                <div>
                  <label className="block text-slate-400 mb-1 font-medium">Username Prefix</label>
                  <select
                    value={passPrefix}
                    onChange={(e) => setPassPrefix(e.target.value as any)}
                    className="w-full px-2.5 py-1.5 bg-slate-900 border border-slate-700/80 rounded-lg text-white text-xs focus:outline-none focus:ring-1 focus:ring-blue-500"
                  >
                    <option value="AGENT">AGENT-####</option>
                    <option value="USER">USER-####</option>
                    <option value="CLIENT">CLIENT-####</option>
                    <option value="MEMBER">MEMBER-####</option>
                  </select>
                </div>

                <div>
                  <label className="block text-slate-400 mb-1 font-medium">Recipient / Label (Optional)</label>
                  <input
                    type="text"
                    value={passLabel}
                    onChange={(e) => setPassLabel(e.target.value)}
                    placeholder="e.g. Tokyo Field Auditor"
                    className="w-full px-2.5 py-1.5 bg-slate-900 border border-slate-700/80 rounded-lg text-white text-xs placeholder-slate-500 focus:outline-none focus:ring-1 focus:ring-blue-500"
                  />
                </div>
              </div>
            </div>

            {/* Banner for newly generated pass */}
            <AnimatePresence>
              {latestGeneratedPass && (
                <motion.div
                  initial={{ opacity: 0, y: -10 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, y: -10 }}
                  className="p-4 rounded-xl bg-emerald-950/40 border border-emerald-700/60 text-xs text-emerald-200 flex flex-col sm:flex-row sm:items-center justify-between gap-3 shadow-lg"
                >
                  <div className="flex items-center gap-3">
                    <div className="w-10 h-10 rounded-xl bg-emerald-500/20 text-emerald-400 flex items-center justify-center shrink-0">
                      <CheckCircle2 className="w-6 h-6" />
                    </div>
                    <div>
                      <span className="font-semibold text-emerald-300 block text-sm">
                        New Passcode Auto-Generated!
                      </span>
                      <div className="flex items-center gap-3 font-mono text-xs mt-0.5">
                        <span>User: <strong className="text-white text-sm">{latestGeneratedPass.username}</strong></span>
                        <span>•</span>
                        <span>Pass: <strong className="text-amber-300 text-sm">{latestGeneratedPass.passcode}</strong></span>
                        <span>•</span>
                        <span className="uppercase text-[10px] px-1.5 py-0.2 bg-emerald-900/60 rounded text-emerald-300 font-sans">
                          {latestGeneratedPass.role}
                        </span>
                      </div>
                    </div>
                  </div>

                  <button
                    type="button"
                    onClick={() => handleCopyCredentials(latestGeneratedPass)}
                    className="px-3 py-1.5 bg-emerald-600 hover:bg-emerald-500 text-white font-medium rounded-lg flex items-center justify-center gap-1.5 transition-colors cursor-pointer shrink-0"
                  >
                    {copiedId === latestGeneratedPass.id ? (
                      <>
                        <Check className="w-3.5 h-3.5" />
                        <span>Copied!</span>
                      </>
                    ) : (
                      <>
                        <Copy className="w-3.5 h-3.5" />
                        <span>Copy Credentials</span>
                      </>
                    )}
                  </button>
                </motion.div>
              )}
            </AnimatePresence>

            {/* Issued Access Passes Table */}
            <div className="space-y-3">
              <div className="flex items-center justify-between">
                <h4 className="text-xs font-semibold text-slate-300 uppercase tracking-wider">
                  Active Passcode Registry ({accessPasses.length})
                </h4>
                <span className="text-[11px] text-slate-500">
                  Credentials grant access to the database
                </span>
              </div>

              <div className="bg-slate-900/80 border border-slate-800 rounded-xl overflow-hidden shadow-md">
                <div className="overflow-x-auto">
                  <table className="w-full text-left border-collapse text-xs">
                    <thead>
                      <tr className="border-b border-slate-800 bg-slate-950/60 text-[11px] uppercase tracking-wider font-semibold text-slate-400">
                        <th className="py-2.5 px-4">Auto-Generated Username</th>
                        <th className="py-2.5 px-4">Passcode</th>
                        <th className="py-2.5 px-4">Role</th>
                        <th className="py-2.5 px-4">Status</th>
                        <th className="py-2.5 px-4">Usage</th>
                        <th className="py-2.5 px-4 text-right">Actions</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-slate-800/60 text-slate-300 font-mono">
                      {accessPasses.map((pass) => {
                        const isVisible = showPasscodes[pass.id];

                        return (
                          <tr key={pass.id} className="hover:bg-slate-800/30 transition-colors">
                            {/* Username */}
                            <td className="py-3 px-4 font-semibold text-white">
                              <div className="flex items-center gap-2">
                                <span>{pass.username}</span>
                                {pass.label && (
                                  <span className="font-sans text-[10px] text-slate-500 truncate max-w-[120px]">
                                    ({pass.label})
                                  </span>
                                )}
                              </div>
                            </td>

                            {/* Passcode */}
                            <td className="py-3 px-4 text-amber-300">
                              <div className="flex items-center gap-2">
                                <span>{isVisible ? pass.passcode : '••••-••••'}</span>
                                <button
                                  type="button"
                                  onClick={() =>
                                    setShowPasscodes((prev) => ({
                                      ...prev,
                                      [pass.id]: !prev[pass.id],
                                    }))
                                  }
                                  className="text-slate-500 hover:text-slate-300 p-0.5"
                                  title={isVisible ? 'Hide Passcode' : 'Show Passcode'}
                                >
                                  {isVisible ? <EyeOff className="w-3.5 h-3.5" /> : <Eye className="w-3.5 h-3.5" />}
                                </button>
                              </div>
                            </td>

                            {/* Role */}
                            <td className="py-3 px-4 font-sans">
                              <span className={`px-2 py-0.5 rounded text-[10px] font-semibold ${
                                pass.role === 'editor'
                                  ? 'bg-purple-950 text-purple-300 border border-purple-800'
                                  : 'bg-blue-950 text-blue-300 border border-blue-800'
                              }`}>
                                {pass.role}
                              </span>
                            </td>

                            {/* Status Toggle */}
                            <td className="py-3 px-4 font-sans">
                              <button
                                type="button"
                                onClick={() => handleTogglePassActive(pass.id)}
                                className={`px-2 py-0.5 rounded-full text-[10px] font-semibold flex items-center gap-1 transition-colors cursor-pointer ${
                                  pass.isActive
                                    ? 'bg-emerald-950 text-emerald-300 border border-emerald-800'
                                    : 'bg-rose-950 text-rose-400 border border-rose-800'
                                }`}
                              >
                                <span className={`w-1.5 h-1.5 rounded-full ${
                                  pass.isActive ? 'bg-emerald-400' : 'bg-rose-500'
                                }`} />
                                <span>{pass.isActive ? 'Active' : 'Revoked'}</span>
                              </button>
                            </td>

                            {/* Usage Count */}
                            <td className="py-3 px-4 text-slate-400 text-[11px]">
                              {pass.usageCount} logins
                            </td>

                            {/* Actions */}
                            <td className="py-3 px-4 text-right font-sans">
                              <div className="flex items-center justify-end gap-1.5">
                                <button
                                  type="button"
                                  onClick={() => handleCopyCredentials(pass)}
                                  className="p-1 text-slate-400 hover:text-white rounded hover:bg-slate-800"
                                  title="Copy Username & Passcode"
                                >
                                  {copiedId === pass.id ? (
                                    <Check className="w-3.5 h-3.5 text-emerald-400" />
                                  ) : (
                                    <Copy className="w-3.5 h-3.5" />
                                  )}
                                </button>

                                <button
                                  type="button"
                                  onClick={() => handleRegeneratePasscode(pass.id)}
                                  className="p-1 text-slate-400 hover:text-amber-400 rounded hover:bg-slate-800"
                                  title="Auto-Regenerate New Passcode for this User"
                                >
                                  <RefreshCw className="w-3.5 h-3.5" />
                                </button>

                                <button
                                  type="button"
                                  onClick={() => handleDeletePass(pass.id)}
                                  className="p-1 text-slate-400 hover:text-rose-400 rounded hover:bg-slate-800"
                                  title="Delete Pass"
                                >
                                  <Trash2 className="w-3.5 h-3.5" />
                                </button>
                              </div>
                            </td>
                          </tr>
                        );
                      })}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        )}

        {/* Tab 2: Custom Fields Builder */}
        {activeTab === 'schema' && (
          <div className="flex-1 overflow-y-auto p-6 space-y-6">
            {/* Create Field Form */}
            <div className="p-5 rounded-2xl bg-slate-900/80 border border-slate-800 shadow-md">
              <h3 className="text-xs font-semibold text-purple-400 uppercase tracking-wider mb-1 flex items-center gap-1.5">
                <Plus className="w-3.5 h-3.5" />
                Add New Dynamic Custom Field
              </h3>
              <p className="text-xs text-slate-400 mb-4">
                Define schema fields. Any field you create will instantly become available across all profile forms, table columns, and detail views.
              </p>

              {fieldSuccessMsg && (
                <div className="mb-4 p-3 rounded-xl bg-emerald-950/40 border border-emerald-800 text-emerald-300 text-xs flex items-center gap-2">
                  <CheckCircle2 className="w-4 h-4 shrink-0" />
                  <span>{fieldSuccessMsg}</span>
                </div>
              )}

              <form onSubmit={handleCreateField} className="space-y-4 text-xs">
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                  <div>
                    <label className="block font-medium text-slate-300 mb-1">
                      Field Label <span className="text-rose-400">*</span>
                    </label>
                    <input
                      type="text"
                      value={fieldLabel}
                      onChange={(e) => setFieldLabel(e.target.value)}
                      placeholder="e.g. Security Clearance, Emergency Contact"
                      className="w-full px-3 py-2 bg-slate-950 border border-slate-700/80 rounded-xl text-white placeholder-slate-500 focus:outline-none focus:ring-2 focus:ring-purple-500"
                      required
                    />
                  </div>

                  <div>
                    <label className="block font-medium text-slate-300 mb-1">
                      Field Data Type
                    </label>
                    <select
                      value={fieldType}
                      onChange={(e) => setFieldType(e.target.value as CustomFieldType)}
                      className="w-full px-3 py-2 bg-slate-950 border border-slate-700/80 rounded-xl text-white focus:outline-none focus:ring-2 focus:ring-purple-500"
                    >
                      <option value="text">Text (Single Line)</option>
                      <option value="number">Number</option>
                      <option value="date">Date</option>
                      <option value="select">Dropdown Select</option>
                      <option value="badge">Badge Pill</option>
                      <option value="url">Web URL / Link</option>
                      <option value="email">Email</option>
                      <option value="boolean">Yes / No Toggle</option>
                    </select>
                  </div>

                  {(fieldType === 'select' || fieldType === 'badge') && (
                    <div className="sm:col-span-2">
                      <label className="block font-medium text-slate-300 mb-1">
                        Dropdown Options (comma separated)
                      </label>
                      <input
                        type="text"
                        value={fieldOptions}
                        onChange={(e) => setFieldOptions(e.target.value)}
                        placeholder="e.g. Low, Medium, High, Urgent"
                        className="w-full px-3 py-2 bg-slate-950 border border-slate-700/80 rounded-xl text-white placeholder-slate-500 focus:outline-none focus:ring-2 focus:ring-purple-500"
                      />
                    </div>
                  )}

                  <div>
                    <label className="block font-medium text-slate-300 mb-1">
                      Placeholder Text (Optional)
                    </label>
                    <input
                      type="text"
                      value={fieldPlaceholder}
                      onChange={(e) => setFieldPlaceholder(e.target.value)}
                      placeholder="e.g. Enter badge ID..."
                      className="w-full px-3 py-2 bg-slate-950 border border-slate-700/80 rounded-xl text-white placeholder-slate-500 focus:outline-none focus:ring-2 focus:ring-purple-500"
                    />
                  </div>

                  <div className="flex items-center gap-6 pt-6">
                    <label className="flex items-center gap-2 cursor-pointer">
                      <input
                        type="checkbox"
                        checked={fieldShowInTable}
                        onChange={(e) => setFieldShowInTable(e.target.checked)}
                        className="w-4 h-4 text-purple-600 rounded bg-slate-900 border-slate-700"
                      />
                      <span className="text-slate-300">Show in Table View</span>
                    </label>

                    <label className="flex items-center gap-2 cursor-pointer">
                      <input
                        type="checkbox"
                        checked={fieldRequired}
                        onChange={(e) => setFieldRequired(e.target.checked)}
                        className="w-4 h-4 text-purple-600 rounded bg-slate-900 border-slate-700"
                      />
                      <span className="text-slate-300">Required Field</span>
                    </label>
                  </div>
                </div>

                <div className="pt-2 flex justify-end">
                  <button
                    type="submit"
                    className="px-4 py-2 bg-purple-600 hover:bg-purple-500 text-white font-medium rounded-xl flex items-center gap-1.5 shadow-md transition-all cursor-pointer"
                  >
                    <Plus className="w-3.5 h-3.5" />
                    <span>Create Custom Field</span>
                  </button>
                </div>
              </form>
            </div>

            {/* List of Custom Fields */}
            <div className="space-y-3">
              <h4 className="text-xs font-semibold text-slate-300 uppercase tracking-wider">
                Configured Database Schema Fields ({customFields.length})
              </h4>

              <div className="space-y-2">
                {customFields.map((field) => (
                  <div
                    key={field.id}
                    className="p-3 bg-slate-900/80 border border-slate-800 rounded-xl flex items-center justify-between gap-3 text-xs"
                  >
                    <div className="flex items-center gap-3">
                      <span className="px-2 py-0.5 rounded text-[11px] font-mono font-semibold bg-purple-950 text-purple-300 border border-purple-800">
                        {field.type}
                      </span>
                      <div>
                        <div className="font-semibold text-white flex items-center gap-2">
                          <span>{field.label}</span>
                          <code className="text-[11px] text-slate-500 font-mono">[{field.key}]</code>
                        </div>
                        {field.options && (
                          <div className="text-[11px] text-slate-400 mt-0.5">
                            Options: {field.options.join(', ')}
                          </div>
                        )}
                      </div>
                    </div>

                    <div className="flex items-center gap-3">
                      <button
                        type="button"
                        onClick={() => handleToggleFieldTable(field.id)}
                        className={`text-[11px] px-2 py-0.5 rounded font-medium transition-colors ${
                          field.showInTable
                            ? 'bg-blue-950 text-blue-300 border border-blue-800'
                            : 'bg-slate-800 text-slate-400'
                        }`}
                      >
                        {field.showInTable ? 'In Table View' : 'Hidden in Table'}
                      </button>

                      <button
                        type="button"
                        onClick={() => handleDeleteField(field.id)}
                        className="p-1.5 text-slate-400 hover:text-rose-400 rounded hover:bg-slate-800 transition-colors"
                        title="Delete Field"
                      >
                        <Trash2 className="w-3.5 h-3.5" />
                      </button>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        )}

        {/* Tab: Google Drive Backend */}
        {activeTab === 'drive' && (
          <GoogleDriveTab
            driveConfig={driveConfig}
            profiles={profiles}
            customFields={customFields}
            accessPasses={accessPasses}
            onSaveDriveConfig={onUpdateDriveConfig}
            onImportDriveData={onImportDriveData}
          />
        )}

        {/* Tab: API & Web Form Sync */}
        {activeTab === 'api' && (
          <ApiConfigTab
            apiConfig={apiConfig}
            profiles={profiles}
            onSaveConfig={onUpdateApiConfig}
          />
        )}

        {/* Tab 3: Python Backend Hub */}
        {activeTab === 'python' && (
          <div className="flex-1 overflow-y-auto p-6 space-y-4 text-xs">
            <div className="p-4 rounded-xl bg-slate-900 border border-slate-800">
              <div className="flex items-center justify-between mb-2">
                <div className="flex items-center gap-2">
                  <Terminal className="w-4 h-4 text-emerald-400" />
                  <h3 className="text-sm font-semibold text-white">
                    Python SQLite Database & Passcode Generator
                  </h3>
                </div>
                <button
                  type="button"
                  onClick={onOpenPythonHub}
                  className="px-3 py-1.5 bg-emerald-600 hover:bg-emerald-500 text-white rounded-lg text-xs font-medium transition-colors cursor-pointer"
                >
                  Open Full Python Studio
                </button>
              </div>
              <p className="text-slate-400 text-xs leading-relaxed">
                A complete standalone Python script (<code className="text-emerald-300">database.py</code>) is included directly in the root directory. It runs using Python 3.10 standard library without needing external packages, featuring SQLite persistence, auto-generated access passcodes, and an optional HTTP REST API.
              </p>
            </div>

            <div className="p-4 rounded-xl bg-slate-900 border border-slate-800 space-y-3 font-mono">
              <h4 className="font-sans text-xs font-semibold text-slate-300">
                Quick Terminal Execution
              </h4>
              <div className="p-3 bg-black/70 rounded-lg text-emerald-400 space-y-1">
                <div># 1. Initialize SQLite Database Schema</div>
                <div className="text-white">$ python3 database.py --init</div>
                <div className="mt-2"># 2. Auto-Generate New Access Pass via Python secrets</div>
                <div className="text-white">$ python3 database.py --generate-pass</div>
                <div className="mt-2"># 3. List All Active Profiles</div>
                <div className="text-white">$ python3 database.py --list-profiles</div>
                <div className="mt-2"># 4. Start Python HTTP API on port 8080</div>
                <div className="text-white">$ python3 database.py --serve</div>
              </div>
            </div>
          </div>
        )}

        {/* Tab 4: Database Settings & Backup */}
        {activeTab === 'settings' && (
          <div className="flex-1 overflow-y-auto p-6 space-y-6 text-xs">
            {/* Backup & Restore */}
            <div className="p-4 rounded-xl bg-slate-900 border border-slate-800 space-y-3">
              <h3 className="text-sm font-semibold text-white flex items-center gap-2">
                <Database className="w-4 h-4 text-blue-400" />
                Data Backup & Migration
              </h3>
              <p className="text-slate-400">
                Export all current profile records, dynamic schema fields, and access passcodes to a JSON file or restore from a backup.
              </p>
              <div className="flex flex-wrap gap-3 pt-1">
                <button
                  type="button"
                  onClick={handleExportJSON}
                  className="px-4 py-2 bg-slate-800 hover:bg-slate-700 text-slate-200 rounded-xl font-medium flex items-center gap-2 transition-colors cursor-pointer"
                >
                  <Download className="w-3.5 h-3.5 text-blue-400" />
                  <span>Export Database to JSON</span>
                </button>

                <label className="px-4 py-2 bg-slate-800 hover:bg-slate-700 text-slate-200 rounded-xl font-medium flex items-center gap-2 transition-colors cursor-pointer">
                  <Upload className="w-3.5 h-3.5 text-indigo-400" />
                  <span>Import Database JSON</span>
                  <input
                    type="file"
                    accept=".json"
                    onChange={handleImportJSON}
                    className="hidden"
                  />
                </label>

                <button
                  type="button"
                  onClick={() => {
                    if (confirm('Reset database to clean initial demonstration state?')) {
                      onResetDatabase();
                    }
                  }}
                  className="px-4 py-2 bg-rose-950/40 hover:bg-rose-900/60 text-rose-300 border border-rose-800/60 rounded-xl font-medium flex items-center gap-2 transition-colors cursor-pointer ml-auto"
                >
                  <RotateCcw className="w-3.5 h-3.5" />
                  <span>Reset Demo Records</span>
                </button>
              </div>
            </div>

            {/* Change Master PIN */}
            <div className="p-4 rounded-xl bg-slate-900 border border-slate-800 space-y-3">
              <h3 className="text-sm font-semibold text-white flex items-center gap-2">
                <Lock className="w-4 h-4 text-amber-400" />
                Administrator Master PIN
              </h3>
              <p className="text-slate-400">
                Change the master PIN used to unlock the Administrator Portal. Current PIN is active.
              </p>

              {pinChangeMsg && (
                <div className="p-2.5 rounded-lg bg-emerald-950/40 border border-emerald-800 text-emerald-300 flex items-center gap-2">
                  <CheckCircle2 className="w-4 h-4" />
                  <span>{pinChangeMsg}</span>
                </div>
              )}

              <form onSubmit={handleChangePin} className="flex gap-2 max-w-sm">
                <input
                  type="password"
                  value={newPin}
                  onChange={(e) => setNewPin(e.target.value)}
                  placeholder="Enter new 4+ digit PIN"
                  className="flex-1 px-3 py-2 bg-slate-950 border border-slate-700/80 rounded-xl text-white font-mono placeholder-slate-500 focus:outline-none focus:ring-1 focus:ring-amber-500"
                  minLength={4}
                  required
                />
                <button
                  type="submit"
                  className="px-4 py-2 bg-amber-600 hover:bg-amber-500 text-white rounded-xl font-medium transition-colors cursor-pointer shrink-0"
                >
                  Update PIN
                </button>
              </form>
            </div>
          </div>
        )}
      </motion.div>
    </div>
  );
};
