import { AccessPass } from '../types';

const PREFIXES = ['USER', 'AGENT', 'CLIENT', 'MEMBER', 'SECURE', 'DEV', 'ADMIN'];
const PASS_CHARS = '23456789ABCDEFGHJKLMNPQRSTUVWXYZ'; // omitting ambiguous chars 0, 1, I, O

/**
 * Automatically generates a secure, human-friendly username without typing
 * e.g. "USER-8419" or "AGENT-5291"
 */
export function autoGenerateUsername(customPrefix?: string): string {
  const prefix = customPrefix || PREFIXES[Math.floor(Math.random() * PREFIXES.length)];
  const randomDigits = Math.floor(1000 + Math.random() * 9000);
  return `${prefix}-${randomDigits}`;
}

/**
 * Automatically generates a high-entropy formatted passcode without typing
 * e.g. "7K9M-4N2P" (8 characters, grouped into 4-4 with hyphen)
 */
export function autoGeneratePasscode(): string {
  let part1 = '';
  let part2 = '';
  for (let i = 0; i < 4; i++) {
    part1 += PASS_CHARS.charAt(Math.floor(Math.random() * PASS_CHARS.length));
    part2 += PASS_CHARS.charAt(Math.floor(Math.random() * PASS_CHARS.length));
  }
  return `${part1}-${part2}`;
}

/**
 * Factory to create a fully auto-generated AccessPass object in 1 click
 */
export function createAutoGeneratedPass(options?: {
  role?: 'viewer' | 'editor';
  label?: string;
  prefix?: string;
}): AccessPass {
  const id = 'pass_' + Date.now().toString(36) + '_' + Math.random().toString(36).substring(2, 7);
  const username = autoGenerateUsername(options?.prefix);
  const passcode = autoGeneratePasscode();

  return {
    id,
    username,
    passcode,
    role: options?.role || 'viewer',
    label: options?.label || `Auto-Generated Pass (${username})`,
    createdAt: new Date().toISOString(),
    usageCount: 0,
    isActive: true,
  };
}
